Refresh base pipeline from latest template

diff --git a/ci/repipe b/ci/repipe
--- a/ci/repipe
+++ b/ci/repipe
@@ -5,20 +5,21 @@
 # Script for merging together pipeline configuration files
 # (via Spruce!) and configuring Concourse.
 #
-# author:  James Hunt <james@niftylogic.com>
-#          Dennis Bell <dennis.j.bell@gmail.com>
-# created: 2016-03-04
+# original authors: James Hunt <james@niftylogic.com>
+#                   Dennis Bell <dennis.j.bell@gmail.com>
+# created:          2016-03-04
+# maintainer:       Benjamin Gandon (Gstack)
 
 need_command() {
-	local cmd=${1:?need_command() - no command name given}
+    local cmd=${1:?"need_command() - no command name given"}
 
-	if [[ ! -x "$(command -v $cmd)" ]]; then
-		echo >&2 "${cmd} is not installed."
-		if [[ "${cmd}" == "spruce" ]]; then
-			echo >&2 "Please download it from https://github.com/geofffranks/spruce/releases"
-		fi
-		exit 2
-	fi
+    if [[ ! -x "$(command -v ${cmd})" ]]; then
+        echo >&2 "${cmd} is not installed."
+        if [[ "${cmd}" == "spruce" ]]; then
+            echo >&2 "Please download it from https://github.com/geofffranks/spruce/releases"
+        fi
+        exit 2
+    fi
 }
 
 NO_FLY=
@@ -45,33 +46,35 @@ usage() {
 }
 
 open_pipeline() {
-	url=$(show_pipeline_url)
+    url=$(show_pipeline_url)
     cleanup
-	if [[ -x /usr/bin/open ]]; then
-		exec /usr/bin/open "$url"
-	else
-		echo "Sorry, but I was not able to automagically open"
-		echo "your Concourse Pipeline in the browser."
-		echo
-		echo "Here's a link you can click on, though:"
-		echo
-		echo "  $url"
-		echo
-		exit 0;
-	fi
+    if [[ -x /usr/bin/open ]]; then
+        exec /usr/bin/open "${url}"
+    else
+        echo "Sorry, but I was not able to automagically open"
+        echo "your Concourse Pipeline in the browser."
+        echo
+        echo "Here's a link you can click on, though:"
+        echo
+        echo "  ${url}"
+        echo
+        exit 0;
+    fi
 }
 
 show_pipeline_url() {
-	spruce merge --skip-eval pipeline.yml ${settings_file} > .deploy.yml
-	concourse_url=$(spruce json .deploy.yml | jq -r ".meta.url")
-	team=$(spruce json .deploy.yml | jq -r ".meta.team // \"main\"")
-	pipeline=$(spruce merge --skip-eval \
-		--cherry-pick meta.pipeline \
-		--cherry-pick meta.name \
-		.deploy.yml | spruce merge - | spruce json | jq -r ".meta.pipeline")
-
-	echo "$concourse_url/teams/$team/pipelines/$pipeline"
-	exit 0
+    spruce merge --skip-eval pipeline.yml ${settings_file} > .deploy.yml
+    concourse_url=$(spruce json .deploy.yml | jq -r ".meta.url")
+    team=$(spruce json .deploy.yml | jq -r ".meta.team // \"main\"")
+    pipeline=$(
+        spruce merge --skip-eval \
+            --cherry-pick meta.pipeline \
+            --cherry-pick meta.name \
+            .deploy.yml \
+        | spruce merge - | spruce json | jq -r ".meta.pipeline"
+    )
+    echo "${concourse_url}/teams/${team}/pipelines/${pipeline}"
+    exit 0
 }
 
 for arg do
@@ -90,16 +93,16 @@ for arg do
     esac
 done
 
-cd $(dirname $BASH_SOURCE[0])
+cd "$(dirname "${BASH_SOURCE[0]}")"
 echo >&2 "Working in $(pwd)"
 need_command spruce
 
 # Allow for target-specific settings
 settings_file="$(ls -1 settings.yml ${CONCOURSE_TARGET:+"settings-${CONCOURSE_TARGET}.yml"} 2>/dev/null | head -n1)"
-if [[ -z "$settings_file" ]]
+if [[ -z "${settings_file}" ]]
 then
-  echo >&2 "Missing local settings in ci/settings.yml${CONCOURSE_TARGET:+" or ci/settings-${CONCOURSE_TARGET}.yml"}!"
-  exit 1
+    echo >&2 "Missing local settings in ci/settings.yml${CONCOURSE_TARGET:+" or ci/settings-${CONCOURSE_TARGET}.yml"}!"
+    exit 1
 fi
 
 echo >&2 "Using settings found in ${settings_file}"
@@ -113,26 +116,26 @@ trap "cleanup" QUIT TERM EXIT INT
 spruce merge pipeline.yml ${settings_file} > .deploy.yml
 PIPELINE=$(spruce json .deploy.yml | jq -r '.meta.pipeline // ""')
 if [[ -z ${PIPELINE} ]]; then
-	echo >&2 "Missing pipeline name in ci/settings.yml!"
-	exit 1
+    echo >&2 "Missing pipeline name in ci/settings.yml!"
+    exit 1
 fi
 
 TARGET_FROM_SETTINGS=$(spruce json .deploy.yml | jq -r '.meta.target // ""')
 if [[ -z ${CONCOURSE_TARGET} ]]; then
-  TARGET=${TARGET_FROM_SETTINGS}
-elif [[ "$CONCOURSE_TARGET" != "$TARGET_FROM_SETTINGS" ]]
+    TARGET=${TARGET_FROM_SETTINGS}
+elif [[ "${CONCOURSE_TARGET}" != "${TARGET_FROM_SETTINGS}" ]]
 then
-  echo >&2 "Target in {$settings_file} differs from target in \$CONCOURSE_TARGET"
-  echo >&2 "  \$CONCOURSE_TARGET: $CONCOURSE_TARGET"
-  echo >&2 "  Target in file:    $TARGET_FROM_SETTINGS"
-  exit 1
+    echo >&2 "Target in {${settings_file}} differs from target in \$CONCOURSE_TARGET"
+    echo >&2 "  \$CONCOURSE_TARGET: ${CONCOURSE_TARGET}"
+    echo >&2 "  Target in file:    ${TARGET_FROM_SETTINGS}"
+    exit 1
 else
-  TARGET=${CONCOURSE_TARGET}
+    TARGET=${CONCOURSE_TARGET}
 fi
 
 if [[ -z ${TARGET} ]]; then
-	echo >&2 "Missing Concourse Target in ci/settings.yml!"
-	exit 1
+    echo >&2 "Missing Concourse Target in ci/settings.yml!"
+    exit 1
 fi
 
 fly_cmd="${FLY_CMD:-fly}"
@@ -146,6 +149,6 @@ case "${VALIDATE_PIPELINE}" in
 esac
 
 set +x
-$fly_cmd --target ${TARGET} ${fly_opts} --config .deploy.yml
+${fly_cmd} --target ${TARGET} ${fly_opts} --config .deploy.yml
 [[ -n ${VALIDATE_PIPELINE} ]] && exit 0
-$fly_cmd --target ${TARGET} unpause-pipeline --pipeline ${PIPELINE}
+${fly_cmd} --target ${TARGET} unpause-pipeline --pipeline ${PIPELINE}
diff --git a/ci/scripts/release b/ci/scripts/release
--- a/ci/scripts/release
+++ b/ci/scripts/release
@@ -5,60 +5,63 @@
 # Script for generating Github release / tag assets
 # and managing release notes for a Docker Image pipeline
 #
-# author:  James Hunt <james@niftylogic.com>
-#          Dennis Bell <dennis.j.bell@gmail.com>
-# created: 2016-03-04
+# original authors: James Hunt <james@niftylogic.com>
+#                   Dennis Bell <dennis.j.bell@gmail.com>
+# created:          2016-03-04
+# maintainer:       Benjamin Gandon (Gstack)
 
 set -eu
 
-: ${REPO_ROOT:?required}
-: ${RELEASE_ROOT:?required}
-: ${RELEASE_NAME:?required}
-: ${GIT_EMAIL:?required}
-: ${GIT_NAME:?required}
+: ${REPO_ROOT:?"required"}
+: ${RELEASE_ROOT:?"required"}
+: ${RELEASE_NAME:?"required"}
+: ${GIT_EMAIL:?"required"}
+: ${GIT_NAME:?"required"}
 RELEASE_BRANCH=${RELEASE_BRANCH:-"master"}
-: ${REPO_OUT:?required}
+: ${REPO_OUT:?"required"}
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
+    echo >&2 "ci/release_notes.md not found. Did you forget to write them?"
+    exit 1
 fi
 
-if [[ -z ${VERSION_FROM} ]]; then
-  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
-  exit 2
+if [[ -z "${VERSION_FROM}" ]]; then
+    echo >&2 "VERSION_FROM environment variable not set, or empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) not found. Did you misconfigure Concourse?"
+    exit 2
 fi
-VERSION=$(cat ${VERSION_FROM})
-if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
+version=$(cat ${VERSION_FROM})
+if [[ -z "${version}" ]]; then
+    echo >&2 "Version file (${VERSION_FROM}) was empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 
-echo "v${VERSION}"                  > ${RELEASE_ROOT}/tag
-echo "${RELEASE_NAME} v${VERSION}"  > ${RELEASE_ROOT}/name
+echo "v${version}"                  > ${RELEASE_ROOT}/tag
+echo "${RELEASE_NAME} v${version}"  > ${RELEASE_ROOT}/name
 mv ${REPO_ROOT}/ci/release_notes.md   ${RELEASE_ROOT}/notes.md
 
 # GIT!
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "${GIT_EMAIL}"
+    git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "${GIT_NAME}"
+    git config --global user.name "${GIT_NAME}"
 fi
 
-(cd ${REPO_ROOT}
- git merge --no-edit "${RELEASE_BRANCH}"
- git add -A
- git status
- git commit -m "release v${VERSION} [skip ci]")
+(
+    cd ${REPO_ROOT}
+    git merge --no-edit "${RELEASE_BRANCH}"
+    git add -A
+    git status
+    git commit -m "release v${version} [skip ci]"
+)
 
 # so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}
 
 sed -e '/START_OF_DOCKERHUB_STRIP/,/END_OF_DOCKERHUB_STRIP/d' \
-  git/README.md \
-  > dockerhub/README.md
+        git/README.md \
+    > dockerhub/README.md
